// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtOO3Qj3lwRRWriaLbEZivcozvldy6eas',
    appId: '1:532584395775:web:96d6532b1b95b9448c6dca',
    messagingSenderId: '532584395775',
    projectId: 'test-1563438049939',
    authDomain: 'test-1563438049939.firebaseapp.com',
    storageBucket: 'test-1563438049939.appspot.com',
    measurementId: 'G-4LX3WL5C5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpasJLQ6UIcin_Zj0dJLg5Y4NHIp3s8qA',
    appId: '1:532584395775:android:767aba02e8926eda8c6dca',
    messagingSenderId: '532584395775',
    projectId: 'test-1563438049939',
    storageBucket: 'test-1563438049939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrsIFFsOWJM8SevPGaMA8nHXrm5_ciGI',
    appId: '1:532584395775:ios:9d9ffda3bff9df7e8c6dca',
    messagingSenderId: '532584395775',
    projectId: 'test-1563438049939',
    storageBucket: 'test-1563438049939.appspot.com',
    androidClientId: '532584395775-nru0jvballfrsurhtiat7jgpbkhr33nl.apps.googleusercontent.com',
    iosClientId: '532584395775-vfha2e74omins0urjps2qljq9iv2bbnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwrsIFFsOWJM8SevPGaMA8nHXrm5_ciGI',
    appId: '1:532584395775:ios:cc099e76679329f58c6dca',
    messagingSenderId: '532584395775',
    projectId: 'test-1563438049939',
    storageBucket: 'test-1563438049939.appspot.com',
    androidClientId: '532584395775-nru0jvballfrsurhtiat7jgpbkhr33nl.apps.googleusercontent.com',
    iosClientId: '532584395775-1i8icsnasq8b2aj854g91gebfgr08vcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vapps.RunnerTests',
  );
}
